Update .zshrc

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -158,11 +158,11 @@ alias repos='cd ~/work/repos'
 # update repos by syncing against latest remote
 ru() {
     pushd ~/work/repos >/dev/null || return
-    for dir in */; do		
+    for dir in */; do
 			  dir=${dir%/}
         echo "Processing $dir"
         if [[ -d "$dir/.git" ]]; then
-            (cd "$dir" && git pull --rebase) || echo "Failed: $dir"
+            (cd "$dir" && git pull --rebase --force) || echo "Failed: $dir"
         else
             echo "Skipping $dir (not a git repo)"
         fi
